language: c
compiler:
    - gcc

sudo: false

cache:
  directories:
    - $HOME/install

env:
  global:
    - MERCURY_DASHBOARD_MODEL="Continuous"
    - MERCURY_NO_LOOP="true"
    - MERCURY_DO_COVERAGE="false"
    - MERCURY_DO_MEMCHECK="false"
    - MERCURY_PORT_NAME='tcp://localhost:3344'
  matrix:
    - MERCURY_BUILD_CONFIGURATION="Debug"
    - MERCURY_BUILD_CONFIGURATION="RelWithDebInfo"
    - MERCURY_BUILD_CONFIGURATION="Release"

branches:
  only:
    - master

install:
    - ./Testing/travis_build.sh

before_script:
    - ls -R $HOME/install
    - export PATH=$PATH:$HOME/install/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/lib

script:
    - ctest -VV --output-on-failure -S ./Testing/travis_script.cmake

